name: .Net Build
description: Builds a .NET solution or project

branding:
  color: green
  icon: terminal

inputs:
  script:
    description: List of commands to run with dotnet cli.
    required: true

runs:
  using: composite
  steps:
    - name: Run script with dotnet
      env:
        DOTNET_NOLOGO: 1
        DOTNET_CLI_TELEMETRY_OPTOUT: 1
        DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      shell: bash
      run: ${{ inputs.script }}
